### ISSUE TITLE
scaling

### ISSUE THREAD

**Issue by Aston85** [f2404/torn-userscripts#5]
HI

The issues im exsperiencing is when i maximize the chat window. the top of the windows is hidden behind the bookmark line in the browser. and only way to see the maximize and minimize in chat window is to press F11 to fullscreen

**Comment by f2404** [comment]
Hi, are you talking about this script? "Torn: Chats: Add maximize button"
If yes, you can modify the HEIGHT value on line 13 of the script and make the chat window as big as you like.

**Comment by Aston85** [comment]
yeah its this script look link
[https://prnt.sc/1163gzj](url)

**Comment by Aston85** [comment]
oh sorry.. didnt see your recommendation .. thanks

**Comment by f2404** [comment]
Closing then :)
